meta_product_name: "MoneyCounter"
meta_title: "MoneyCounter - Saving For You"
meta_description: "MoneyCounter is your best friend when it comes to keep track of your Money"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@MoneyCounter"   # required for Twitter Cards
