meta_product_name: "MoneyCounter"
meta_title: "MoneyCounter - We make the saves for you."
meta_description: "MoneyCounter is a App that provides an easy way to track all your expenses and Incomes"
meta_image: "cover.png"
twitter_account: "N/A"
